# Namespace name will be set via --set namespace.name in CI/CD
namespace:
  name: ""

ingress:
  className: traefik
  host: "jukebox.dracocheng.com"
  rules:
    - paths:
        - path: /api
          pathType: Prefix
          serviceName: backend-service
          servicePort: 8000
        - path: /
          pathType: Prefix
          serviceName: frontend-service
          servicePort: 80
